SERVER:
  ENABLED: true
  USER: "test"
  PASS: "test"
  AUTH_ENABLED: false
  INGEST_NODE: false
  TEST_THIRD_PARTY: false
  PORT: 8190
LOGGER:
  LOGLEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER: "localhost:2515"
  GRAYLOG_STREAM: "test"
  DISABLE_STDOUT: false
REDIS:
  HOST: "localhost:6378"
  PASS: test
  DB: 1
  TIMEOUT_DURATION: 500
POSTGRES:
  HOST: localhost
  PORT: 5432
  NAME: gymondo
  USER: test
  PASSWORD: 123456
  SSLMODE: disable
  DEBUG: true
