SERVER:
  ENABLED: true
  USER: "test"
  PASS: "test"
  AUTH_ENABLED: false
  INGEST_NODE: false
  TEST_THIRD_PARTY: false
  PORTS: 8080
LOGGER:
  LOGLEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER: "localhost:2515"
  GRAYLOG_STREAM: "test"
  DISABLE_STDOUT: false
REDIS:
  HOST: "localhost:6379"
  PASS: test
  DB: 1
  TIMEOUT_DURATION: 500
POSTGRES:
  DRIVER_NAME: "postgres"
  DATA_SOURCE: "postgres://root:123456@tcp(localhost:5432)/gymondo"
  TBLES:
    {
      PRODUCTS: "products",
    }